### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by rstacruz** [jsdoc2md/jsdoc-parse#31]
Ironically, jsdoc-parse itself is missing some documentation :) I'd love to know how to use it.

**Comment by 75lb** [comment]
jsdoc-parse by itself isn't too useful, the API is not documented because it's not particularly intended for widespread use. It exists to convert the output from jsdoc3 into data suitable for consumption by a handlebars template (e.g. the one inside jsdoc2md).

It's primarily used by the `jsdoc2md.getTemplateData` method which is [documented here](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#jsdoc2mdgettemplatedataoptions--promise).
