### ISSUE TITLE
Ability to pass in comment directly

### ISSUE THREAD

**Issue by gyandeeps** [jsdoc2md/jsdoc-parse#8]
Add the ability to pass in the comment directly and then getting the parsed object in returned.
Like its done in this lib: https://github.com/Constellation/doctrine

Also I dont want a streamed output rather a return of object would be preferred. That way I can use this module in a synchronous way.

**Comment by 75lb** [comment]
jsdoc *depends* on the input source code being stored in files, because if no value was supplied for the `@module` tag it uses the source code filename instead.. that's why jsdoc does not support passing a string directly.

i am tackling this issue in a new module.. it will also have a synchronous interface which returns the parsed jsdoc data directly.. will let you know once it's ready.

**Comment by gyandeeps** [comment]
@75lb Thanks for the update. Let me know if you need some help on this.

**Comment by 75lb** [comment]
I created a new module [jsdoc-api](https://github.com/jsdoc2md/jsdoc-api) which gives direct, programmatic access to the raw jsdoc output.  It has sync, async and streaming interfaces. You can pass in source code directly (as a string) if required. Does this help?
